ve-set-passwd: pass along whitespace
If the password contains whitespace, make sure it is included in
the argument for ve-hash-passwd. Without this, the help text would
be written insteda of the password hash, locking the user out.

While at it, check the exit code of ve-hash-passwd.

closes https://github.com/victronenergy/venus-private/issues/600

diff --git a/meta-bsp/recipes-bsp/machine-runtime-conf/files/ve-set-passwd b/meta-bsp/recipes-bsp/machine-runtime-conf/files/ve-set-passwd
--- a/meta-bsp/recipes-bsp/machine-runtime-conf/files/ve-set-passwd
+++ b/meta-bsp/recipes-bsp/machine-runtime-conf/files/ve-set-passwd
@@ -22,7 +22,12 @@ passwd="$1"
 if [ "$passwd" = "" ]; then
     hash=""
 else
-    hash="$(ve-hash-passwd $unique_id $passwd)"
+    hash="$(ve-hash-passwd "$unique_id" "$passwd")"
+    if [ $? -ne 0 ]; then
+        echo "could not hash the password"
+        exit 1
+    fi
+
     if [ -z "$hash" ]; then
         echo "could not create password hash"
         exit 1
