venus-install-initramfs, ccgx: base install script on upgrade script
- this adds lcd support for diagnostics.
- the image is now bootable (but for a ccgx only if the nand is empty)
  or R14 is shorted.

perhaps these script can be merged once, the only difference is:
- the install script does program the bootloader / MLO, the upgrade doesn't
- the upgrade script preserves data, install formats it.

diff --git a/meta-venus/recipes-images/venus-install-initramfs/ccgx/swupdate b/meta-venus/recipes-images/venus-install-initramfs/ccgx/swupdate
--- a/meta-venus/recipes-images/venus-install-initramfs/ccgx/swupdate
+++ b/meta-venus/recipes-images/venus-install-initramfs/ccgx/swupdate
@@ -2,14 +2,77 @@
 
 set -e
 
-ubiformat  /dev/mtd12
-ubiattach /dev/ubi_ctrl -m 12
+CARD=/mnt/card
+SWU=${CARD}/venus.swu
+DATA=${CARD}/data.tar
 
+msg() {
+    echo "$@"
+    echo "$@" >/dev/tty0
+}
+
+pause() {
+    while :; do sleep 10; done
+}
+
+error() {
+    test -n "$*" && msg "$*"
+    msg "Error installing software"
+    pause
+}
+
+trap error EXIT
+
+mount -t devtmpfs none /dev
+mount -t proc none /proc
+mount -t sysfs none /sys
+
+modprobe fbcon
+
+msg "Searching for update image..."
+
+for d in sda1 mmcblk0p1; do
+    if mount /dev/$d ${CARD}; then
+        if [ -f ${SWU} ]; then
+            DEV=$d
+            break
+        fi
+        umount ${CARD}
+    fi
+done
+
+if [ -n "${DEV}" ]; then
+    msg "Update image found on ${DEV}"
+else
+    error "Update image not found"
+fi
+
+
+msg "Formatting UBI partition..."
+ubiformat /dev/mtd12
+ubiattach -m 12
 ubimkvol /dev/ubi0 -N rootfs1 -s 200MiB
 ubimkvol /dev/ubi0 -N rootfs2 -s 200MiB
 ubimkvol /dev/ubi0 -N data -s 32MiB
 
-mount /dev/mmcblk0p1 /mnt/card
-swupdate -v -b "0 1 2 3 4 5 6 7 8 9 10 11" -e "stable,copy1" -i /mnt/card/venus.swu
-swupdate -v -b "0 1 2 3 4 5 6 7 8 9 10 11" -e "stable,copy2" -i /mnt/card/venus.swu
-swupdate -v -b "0 1 2 3 4 5 6 7 8 9 10 11" -e "stable,bootloader" -i /mnt/card/venus.swu
+# -b '0..!12..13' tells swupdate ubi volume is on mtd 12 (all others are blacklisted)
+set -- -b "0 1 2 3 4 5 6 7 8 9 10 11 13" -i ${SWU}
+
+msg "Installing rootfs1..."
+swupdate "$@" -e "stable,copy1"
+
+msg "Installing rootfs2..."
+swupdate "$@" -e "stable,copy2"
+
+msg "Installing bootloader..."
+swupdate "$@" -e "stable,bootloader"
+
+msg "updating boot instructions..."
+fw_setenv -s /usr/share/u-boot/u-boot.env
+
+ubidetach -m 12
+umount ${CARD}
+
+msg "Installation complete"
+msg "Remove SD-card and reset system"
+pause
